<a href="https://colab.research.google.com/github/DaltonWise/Homework/blob/main/Final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import json

In [2]:
burden = pd.read_csv('/content/burden-disease-from-each-mental-illness.csv')

#https://ourworldindata.org/mental-health

#DALY explanation: https://www.who.int/data/gho/indicator-metadata-registry/imr-details/158#:~:text=Definition%3A-,One%20DALY%20represents%20the%20loss%20of%20the%20equivalent%20of%20one,health%20condition%20in%20a%20population.

In [4]:
mental_health = pd.read_csv('/content/mental_health_depression_disorder.csv')

#https://www.kaggle.com/datasets/thedevastator/uncover-global-trends-in-mental-health-disorder

<ipython-input-4-b0fb47130264>:1: DtypeWarning: Columns (5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  mental_health = pd.read_csv('/content/mental_health_depression_disorder.csv')

In [9]:
burden.head()

,Entity,Code,Year,"DALYs from depressive disorders per 100,000 people in, both sexes aged age-standardized","DALYs from schizophrenia per 100,000 people in, both sexes aged age-standardized","DALYs from bipolar disorder per 100,000 people in, both sexes aged age-standardized","DALYs from eating disorders per 100,000 people in, both sexes aged age-standardized","DALYs from anxiety disorders per 100,000 people in, both sexes aged age-standardized"
0,Afghanistan,AFG,1990,895.22565,138.24825,147.64412,26.471115,440.33000
1,Afghanistan,AFG,1991,893.88434,137.76122,147.56696,25.548681,439.47202
2,Afghanistan,AFG,1992,892.34973,137.08030,147.13086,24.637949,437.60718
3,Afghanistan,AFG,1993,891.51587,136.48602,146.78812,23.863169,436.69104
4,Afghanistan,AFG,1994,891.39160,136.18323,146.58481,23.189074,436.76800

In [18]:
mental_health.head()

,index,Entity,Code,Year,Schizophrenia (%),Bipolar disorder (%),Eating disorders (%),Anxiety disorders (%),Drug use disorders (%),Depression (%),Alcohol use disorders (%)
0,0,Afghanistan,AFG,1990,0.16056,0.697779,0.101855,4.828830,1.677082,4.071831,0.672404
1,1,Afghanistan,AFG,1991,0.160312,0.697961,0.099313,4.829740,1.684746,4.079531,0.671768
2,2,Afghanistan,AFG,1992,0.160135,0.698107,0.096692,4.831108,1.694334,4.088358,0.670644
3,3,Afghanistan,AFG,1993,0.160037,0.698257,0.094336,4.830864,1.705320,4.096190,0.669738
4,4,Afghanistan,AFG,1994,0.160022,0.698469,0.092439,4.829423,1.716069,4.099582,0.669260

In [ ]:
burden.merge(mental_health, on = 'Entity')
#This was my first merge. I realized I could merge on the first three columns in both dataframes.
#To do that I had to make sure they all had the same data types.

In [15]:
burden['Year'] = burden['Year'].values.astype(str)
mental_health['Year'] = mental_health['Year'].values.astype(str)


#In this cell I am converting each of the year columns to a string. The reason I do this is because when using 'pd.merge' an error was raised stating I was trying to merge a string and a int64.
#I assume that in one of the two data frames the year was a string and the other it was an integer.

#https://sparkbyexamples.com/pandas/pandas-convert-columns-to-string-type/

In [19]:
health_merged = pd.merge(burden, mental_health, on = ['Entity', 'Code', 'Year'])

In [20]:
health_merged

,Entity,Code,Year,"DALYs from depressive disorders per 100,000 people in, both sexes aged age-standardized","DALYs from schizophrenia per 100,000 people in, both sexes aged age-standardized","DALYs from bipolar disorder per 100,000 people in, both sexes aged age-standardized","DALYs from eating disorders per 100,000 people in, both sexes aged age-standardized","DALYs from anxiety disorders per 100,000 people in, both sexes aged age-standardized",index,Schizophrenia (%),Bipolar disorder (%),Eating disorders (%),Anxiety disorders (%),Drug use disorders (%),Depression (%),Alcohol use disorders (%)
0,Afghanistan,AFG,1990,895.22565,138.24825,147.64412,26.471115,440.33000,0,0.16056,0.697779,0.101855,4.82883,1.677082,4.071831,0.672404
1,Afghanistan,AFG,1990,895.22565,138.24825,147.64412,26.471115,440.33000,6659,3.499982,4.647815,12412000,NaN,NaN,NaN,NaN
2,Afghanistan,AFG,1990,895.22565,138.24825,147.64412,26.471115,440.33000,54467,10.318504,4039.755763,12412000,NaN,NaN,NaN,NaN
3,Afghanistan,AFG,1990,895.22565,138.24825,147.64412,26.471115,440.33000,102085,318435.8137,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,AFG,1991,893.88434,137.76122,147.56696,25.548681,439.47202,1,0.160312,0.697961,0.099313,4.82974,1.684746,4.079531,0.671768
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23255,Zimbabwe,ZWE,2017,547.62270,127.46505,115.32798,20.791725,302.88626,108552,340583.1574,NaN,NaN,NaN,NaN,NaN,NaN
23256,Zimbabwe,ZWE,2018,546.57184,127.68121,115.42796,20.916480,301.58250,54274,NaN,NaN,14439000,NaN,NaN,NaN,NaN
23257,Zimbabwe,ZWE,2018,546.57184,127.68121,115.42796,20.916480,301.58250,102082,NaN,NaN,14439000.0,NaN,NaN,NaN,NaN
23258,Zimbabwe,ZWE,2019,544.53160,128.21603,115.38145,21.011127,298.20325,54275,NaN,NaN,14645000,NaN,NaN,NaN,NaN
23259,Zimbabwe,ZWE,2019,544.53160,128.21603,115.38145,21.011127,298.20325,102083,NaN,NaN,14645000.0,NaN,NaN,NaN,NaN

In [25]:
health_merged['Year'].unique()
#Trying to see the range of years in this data set. I would like to try to find world population data from that year range.

array(['1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997',
       '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005',
       '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019'], dtype=object)

In [35]:
world_population = pd.read_excel('/content/world_population_excel.xls', skiprows = [0, 1, 2, 3])

#https://data.worldbank.org/indicator/SP.POP.TOTL?most_recent_year_desc=false

#skipping rows: https://stackoverflow.com/questions/20637439/skip-rows-during-csv-import-pandas

In [36]:
world_population.head()

,Aruba,ABW,"Population, total",SP.POP.TOTL,54608,55811,56682,57475,58178,58782,...,102880,103594,104257,104874,105439,105962,106442,106585,106537,106445
0,Africa Eastern and Southern,AFE,"Population, total",SP.POP.TOTL,130692579.0,134169237.0,137835590.0,141630546.0,145605995.0,149742351.0,...,567892149.0,583651101.0,600008424.0,616377605.0,632746570.0,649757148.0,667242986.0,685112979.0,702977106.0,720839314.0
1,Afghanistan,AFG,"Population, total",SP.POP.TOTL,8622466.0,8790140.0,8969047.0,9157465.0,9355514.0,9565147.0,...,31541209.0,32716210.0,33753499.0,34636207.0,35643418.0,36686784.0,37769499.0,38972230.0,40099462.0,41128771.0
2,Africa Western and Central,AFW,"Population, total",SP.POP.TOTL,97256290.0,99314028.0,101445032.0,103667517.0,105959979.0,108336203.0,...,387204553.0,397855507.0,408690375.0,419778384.0,431138704.0,442646825.0,454306063.0,466189102.0,478185907.0,490330870.0
3,Angola,AGO,"Population, total",SP.POP.TOTL,5357195.0,5441333.0,5521400.0,5599827.0,5673199.0,5736582.0,...,26147002.0,27128337.0,28127721.0,29154746.0,30208628.0,31273533.0,32353588.0,33428486.0,34503774.0,35588987.0
4,Albania,ALB,"Population, total",SP.POP.TOTL,1608800.0,1659800.0,1711319.0,1762621.0,1814135.0,1864791.0,...,2895092.0,2889104.0,2880703.0,2876101.0,2873457.0,2866376.0,2854191.0,2837849.0,2811666.0,2775634.0

In [49]:
world_population2 = pd.read_excel('/content/world_population_excel_2.xls')

#Okay so this is the same data set as the last one. I was having trouble importing the original excel format because of the added cells for explanation in the original data set.
#I am going to email Professor Boal asking with this so that I am doing the project fully.

In [50]:
world_population2

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Aruba,ABW,"Population, total",SP.POP.TOTL,54608.0,55811.0,56682.0,57475.0,58178.0,58782.0,...,102880.0,103594.0,104257.0,104874.0,105439.0,105962.0,106442.0,106585.0,106537.0,106445.0
1,Africa Eastern and Southern,AFE,"Population, total",SP.POP.TOTL,130692579.0,134169237.0,137835590.0,141630546.0,145605995.0,149742351.0,...,567892149.0,583651101.0,600008424.0,616377605.0,632746570.0,649757148.0,667242986.0,685112979.0,702977106.0,720839314.0
2,Afghanistan,AFG,"Population, total",SP.POP.TOTL,8622466.0,8790140.0,8969047.0,9157465.0,9355514.0,9565147.0,...,31541209.0,32716210.0,33753499.0,34636207.0,35643418.0,36686784.0,37769499.0,38972230.0,40099462.0,41128771.0
3,Africa Western and Central,AFW,"Population, total",SP.POP.TOTL,97256290.0,99314028.0,101445032.0,103667517.0,105959979.0,108336203.0,...,387204553.0,397855507.0,408690375.0,419778384.0,431138704.0,442646825.0,454306063.0,466189102.0,478185907.0,490330870.0
4,Angola,AGO,"Population, total",SP.POP.TOTL,5357195.0,5441333.0,5521400.0,5599827.0,5673199.0,5736582.0,...,26147002.0,27128337.0,28127721.0,29154746.0,30208628.0,31273533.0,32353588.0,33428486.0,34503774.0,35588987.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,"Population, total",SP.POP.TOTL,947000.0,966000.0,994000.0,1022000.0,1050000.0,1078000.0,...,1818117.0,1812771.0,1788196.0,1777557.0,1791003.0,1797085.0,1788878.0,1790133.0,1786038.0,1761985.0
262,"Yemen, Rep.",YEM,"Population, total",SP.POP.TOTL,5542459.0,5646668.0,5753386.0,5860197.0,5973803.0,6097298.0,...,26984002.0,27753304.0,28516545.0,29274002.0,30034389.0,30790513.0,31546691.0,32284046.0,32981641.0,33696614.0
263,South Africa,ZAF,"Population, total",SP.POP.TOTL,16520441.0,16989464.0,17503133.0,18042215.0,18603097.0,19187194.0,...,53873616.0,54729551.0,55876504.0,56422274.0,56641209.0,57339635.0,58087055.0,58801927.0,59392255.0,59893885.0
264,Zambia,ZMB,"Population, total",SP.POP.TOTL,3119430.0,3219451.0,3323427.0,3431381.0,3542764.0,3658024.0,...,15234976.0,15737793.0,16248230.0,16767761.0,17298054.0,17835893.0,18380477.0,18927715.0,19473125.0,20017675.0
265,Zimbabwe,ZWE,"Population, total",SP.POP.TOTL,3806310.0,3925952.0,4049778.0,4177931.0,4310332.0,4447149.0,...,13555422.0,13855753.0,14154937.0,14452704.0,14751101.0,15052184.0,15354608.0,15669666.0,15993524.0,16320537.0

In [53]:
population = world_population2.drop(['Indicator Name', 'Indicator Code'], axis = 1)

#Dropping those two columns so that I can hopefully unpivot this data.

In [54]:
population.head()

,Country Name,Country Code,1960,1961,1962,1963,1964,1965,1966,1967,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Aruba,ABW,54608.0,55811.0,56682.0,57475.0,58178.0,58782.0,59291.0,59522.0,...,102880.0,103594.0,104257.0,104874.0,105439.0,105962.0,106442.0,106585.0,106537.0,106445.0
1,Africa Eastern and Southern,AFE,130692579.0,134169237.0,137835590.0,141630546.0,145605995.0,149742351.0,153955516.0,158313235.0,...,567892149.0,583651101.0,600008424.0,616377605.0,632746570.0,649757148.0,667242986.0,685112979.0,702977106.0,720839314.0
2,Afghanistan,AFG,8622466.0,8790140.0,8969047.0,9157465.0,9355514.0,9565147.0,9783147.0,10010030.0,...,31541209.0,32716210.0,33753499.0,34636207.0,35643418.0,36686784.0,37769499.0,38972230.0,40099462.0,41128771.0
3,Africa Western and Central,AFW,97256290.0,99314028.0,101445032.0,103667517.0,105959979.0,108336203.0,110798486.0,113319950.0,...,387204553.0,397855507.0,408690375.0,419778384.0,431138704.0,442646825.0,454306063.0,466189102.0,478185907.0,490330870.0
4,Angola,AGO,5357195.0,5441333.0,5521400.0,5599827.0,5673199.0,5736582.0,5787044.0,5827503.0,...,26147002.0,27128337.0,28127721.0,29154746.0,30208628.0,31273533.0,32353588.0,33428486.0,34503774.0,35588987.0

In [55]:
population = population.set_index(["Country Name", "Country Code"])
population.head()

#Because I am trying to pivot the data, I am converting the country name and country code to the index.
#This will allow me to make the year one single column.

,,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
Country Name,Country Code,,,,,,,,,,,,,,,,,,,,,
Aruba,ABW,54608.0,55811.0,56682.0,57475.0,58178.0,58782.0,59291.0,59522.0,59471.0,59330.0,...,102880.0,103594.0,104257.0,104874.0,105439.0,105962.0,106442.0,106585.0,106537.0,106445.0
Africa Eastern and Southern,AFE,130692579.0,134169237.0,137835590.0,141630546.0,145605995.0,149742351.0,153955516.0,158313235.0,162875171.0,167596160.0,...,567892149.0,583651101.0,600008424.0,616377605.0,632746570.0,649757148.0,667242986.0,685112979.0,702977106.0,720839314.0
Afghanistan,AFG,8622466.0,8790140.0,8969047.0,9157465.0,9355514.0,9565147.0,9783147.0,10010030.0,10247780.0,10494489.0,...,31541209.0,32716210.0,33753499.0,34636207.0,35643418.0,36686784.0,37769499.0,38972230.0,40099462.0,41128771.0
Africa Western and Central,AFW,97256290.0,99314028.0,101445032.0,103667517.0,105959979.0,108336203.0,110798486.0,113319950.0,115921723.0,118615741.0,...,387204553.0,397855507.0,408690375.0,419778384.0,431138704.0,442646825.0,454306063.0,466189102.0,478185907.0,490330870.0
Angola,AGO,5357195.0,5441333.0,5521400.0,5599827.0,5673199.0,5736582.0,5787044.0,5827503.0,5868203.0,5928386.0,...,26147002.0,27128337.0,28127721.0,29154746.0,30208628.0,31273533.0,32353588.0,33428486.0,34503774.0,35588987.0

In [63]:
population2 = population.stack().reset_index()

In [64]:
population2

      Country Name Country Code level_2           0
0            Aruba          ABW    1960     54608.0
1            Aruba          ABW    1961     55811.0
2            Aruba          ABW    1962     56682.0
3            Aruba          ABW    1963     57475.0
4            Aruba          ABW    1964     58178.0
...            ...          ...     ...         ...
16660     Zimbabwe          ZWE    2018  15052184.0
16661     Zimbabwe          ZWE    2019  15354608.0
16662     Zimbabwe          ZWE    2020  15669666.0
16663     Zimbabwe          ZWE    2021  15993524.0
16664     Zimbabwe          ZWE    2022  16320537.0

[16665 rows x 4 columns]

In [67]:
population2.columns = ['Entity', 'Code', 'Year', 'Total_Population']
#Changing the names to match the previous two data sets.

In [68]:
population2.head()

  Entity Code  Year  Total_Population
0  Aruba  ABW  1960           54608.0
1  Aruba  ABW  1961           55811.0
2  Aruba  ABW  1962           56682.0
3  Aruba  ABW  1963           57475.0
4  Aruba  ABW  1964           58178.0

In [77]:
second_merge = pd.merge(health_merged, population2, how = 'left', on = ['Entity', 'Code', 'Year'])

#I used a left merge so that I would only be pulling records from 'population2' that matched records from 'health_merged'.
#I can see by comparing that 'second_merge' and 'health_merged' both have 23,260 rows. I was going to try to right an expression to show that.
#The only thing I could think to do was try to use the shape function to prove they were both the same but they actually have a different number of columns so I cant.
#Either way my point stands that I only returned the records matching from health_merged.

In [80]:
second_merge

,Entity,Code,Year,"DALYs from depressive disorders per 100,000 people in, both sexes aged age-standardized","DALYs from schizophrenia per 100,000 people in, both sexes aged age-standardized","DALYs from bipolar disorder per 100,000 people in, both sexes aged age-standardized","DALYs from eating disorders per 100,000 people in, both sexes aged age-standardized","DALYs from anxiety disorders per 100,000 people in, both sexes aged age-standardized",index,Schizophrenia (%),Bipolar disorder (%),Eating disorders (%),Anxiety disorders (%),Drug use disorders (%),Depression (%),Alcohol use disorders (%),Total_Population
0,Afghanistan,AFG,1990,895.22565,138.24825,147.64412,26.471115,440.33000,0,0.16056,0.697779,0.101855,4.82883,1.677082,4.071831,0.672404,10694796.0
1,Afghanistan,AFG,1990,895.22565,138.24825,147.64412,26.471115,440.33000,6659,3.499982,4.647815,12412000,NaN,NaN,NaN,NaN,10694796.0
2,Afghanistan,AFG,1990,895.22565,138.24825,147.64412,26.471115,440.33000,54467,10.318504,4039.755763,12412000,NaN,NaN,NaN,NaN,10694796.0
3,Afghanistan,AFG,1990,895.22565,138.24825,147.64412,26.471115,440.33000,102085,318435.8137,NaN,NaN,NaN,NaN,NaN,NaN,10694796.0
4,Afghanistan,AFG,1991,893.88434,137.76122,147.56696,25.548681,439.47202,1,0.160312,0.697961,0.099313,4.82974,1.684746,4.079531,0.671768,10745167.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23255,Zimbabwe,ZWE,2017,547.62270,127.46505,115.32798,20.791725,302.88626,108552,340583.1574,NaN,NaN,NaN,NaN,NaN,NaN,14751101.0
23256,Zimbabwe,ZWE,2018,546.57184,127.68121,115.42796,20.916480,301.58250,54274,NaN,NaN,14439000,NaN,NaN,NaN,NaN,15052184.0
23257,Zimbabwe,ZWE,2018,546.57184,127.68121,115.42796,20.916480,301.58250,102082,NaN,NaN,14439000.0,NaN,NaN,NaN,NaN,15052184.0
23258,Zimbabwe,ZWE,2019,544.53160,128.21603,115.38145,21.011127,298.20325,54275,NaN,NaN,14645000,NaN,NaN,NaN,NaN,15354608.0
23259,Zimbabwe,ZWE,2019,544.53160,128.21603,115.38145,21.011127,298.20325,102083,NaN,NaN,14645000.0,NaN,NaN,NaN,NaN,15354608.0

In [79]:
#second_merge.fillna(0)
#I am not sure if I should fill all of these nan values or not yet. It could affect aggregation I think.

**Testing Datasets:**

This section is for uploading data sets to see if they are going to be something we can work through. It is easier for me to get a handle of what I am looking at once I upload it to colab so these are the ones that were not used.

In [ ]:
facility = pd.read_excel('/content/health_facility_locations.xlsx')
facility.head()
facility.columns
facility['FACNAME'].value_counts

In [24]:
#ssi2021 = pd.read_csv('/content/Surgical-Site-Infections-California-Hospitals-2021.csv', encoding='UTF-8')
#https://catalog.data.gov/dataset/surgical-site-infections-ssis-for-operative-procedures-in-california-hospitals-62337

#ssi2022 = pd.read_csv('https://catalog.data.gov/dataset/surgical-site-infections-ssis-for-operative-procedures-in-california-hospitals-62337',)
#https://catalog.data.gov/dataset/surgical-site-infections-ssis-for-operative-procedures-in-california-hospitals-62337

In [ ]:
with open('/content/Surgical-Site-Infections-California-Hospitals-2021.csv') as f:
    print(f)


#When trying to upload these files into colab I am getting an error stating it is unable to

<_io.TextIOWrapper name='/content/Surgical-Site-Infections-California-Hospitals-2021.csv' mode='r' encoding='UTF-8'>

In [ ]:
ocd_patient = pd.read_csv('/content/ocd_patient_dataset.csv')

In [ ]:
vax = pd.read_csv('/content/Special_Vaccine_Locations.csv')

#https://catalog.data.gov/dataset/special-vaccine-locations

vax.head()

In [ ]:
#mi = pd.read_csv('/content/myocardial+infarction+complications.zip')
#mi.head()

social = pd.read_csv('/content/archive.zip')
social.head()

In [ ]:
ocd_patient.head()

In [ ]:
#ocd_json = pd.read_json('https://www.ebi.ac.uk/biostudies/files/S-EPMC2943932/S-EPMC2943932.json')

#ocd_json = json.load(open('/content/OCD.json'))
#ocd_json = pd.DataFrame(ocd_json)

#This is a JSON data set I was trying to juse that kept not running properly. I may use it again but I think because of the way it is formatted it will be tough for me to use.

In [ ]:
student = pd.read_csv('/content/archive (1).zip')
student.head()

**Websites:**

Creating a folder for github:

*   https://berrasari.medium.com/creating-folders-on-github-a-step-by-step-guide-fb0b44b98561#:~:text=Steps%20to%20Create%20Folders%20on%20GitHub&text=Choose%20the%20repository%20where%20you,the%20slash%20at%20the%20end.

Kaggle OCD dataset:

*   https://www.kaggle.com/datasets/ohinhaque/ocd-patient-dataset-demographics-and-clinical-data

Chat gpt webpage week 13 assignment:

*   https://chat.openai.com/share/50db56ab-ffcb-405d-869a-9f4e6f04b76c

Predictors and moderators of treatment outcome in the Pediatric Obsessive Compulsive Treatment Study (POTS I) AND its accompanying JSON file. This is the one that would not work.

*   https://www.ebi.ac.uk/biostudies/europepmc/studies/S-EPMC2943932
*   https://www.ebi.ac.uk/biostudies/files/S-EPMC2943932/S-EPMC2943932.json

Social Media and Mental Health: archive data frame

*   https://www.kaggle.com/datasets/souvikahmed071/social-media-and-mental-health

Student Mental Health: archive(1).zip:

*   https://www.kaggle.com/datasets/shariful07/student-mental-health