<a href="https://colab.research.google.com/github/DaltonWise/Homework/blob/main/Final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Check List:**

1. **data access and formats:**   Sufficient

    I have three files each from a separate website. The file for dataframe 'burden' and dataframe 'mental_health' are both csv format. 'World_populations2' comes from a file in ther excel format.

2. ** data merging: **  Sufficient

    Each of my datasets come from a different website. My first merge is between my 'burden' dataframe and my' mental_health' dataframe creating the 'merge' dataframe. The second merge is between the 'merge' dataframe and the 'world_populations2' dataframe creating 'merge2'.

3. **data aggregation and pivoting:**

      I have unpivoted the 'world_population2' dataframe. I believe this should count as one data transformation. I need to do atleast one more transformation. It will likely be an aggretation of some type.

4. **data transformation:**

    I need to make atleast five field level transformations. I am not sure how many I have done yet.

5. **data visualization:**

    I need to make three or more data visualizations.

6. **Problem applicability:**

    I need to demonstrate the realworld value of this notebook.

7. **Modularity/Style:**

    I need to try to make several functions.

8. **Documentation and Professionalism:**

    Make sure everything is well documented.

**Importing Datasets:**



**What is the purpose?**

To import three different datasets into google colab as dataframes. The dataframes 'burden' and 'mental_health' come from a dataset I found online that were both in csv format. The 'world_population2' dataframe comes from an excel format dataframe. While working on importing the 'world_population' dataset I ran into a road block due to the initial formatting of the dataset as it was downloaded from online. Because the data set was in excel formatting, it had several cells in the first few rows that were there for explanation. The actual dataset did not start until the third row. While trying to import this I was having trouble getting the correct column titles so in order to keep my progress I uploaded a second file of the same data set with those other cells removed. This allowed me to upload the data as I wanted and is where the 'world_population2' dataframe comes from.

**Pseudocode:**

1.   Import the pandas module as pd.
2.   Import the json module.
3.   Import the 'burden-disease-from-each-mental-illness' dataset and assign it to the variable 'burden'.
4.   Import the ''mental_health_depression' dataset and assign it to the variable 'mental_health'.
5.   Import the '/content/world_population_excel_2' dataset and assign it to the variable 'world_population2'.
6.   Show the first five rows of 'burden'.
7.   Show the first five rows of 'mental_health'.
8. Show the first five rows of 'world_populations2'.

In [1]:
import pandas as pd
import json

In [3]:
burden = pd.read_csv('/content/burden-disease-from-each-mental-illness.csv')

#https://ourworldindata.org/mental-health

#DALY explanation: https://www.who.int/data/gho/indicator-metadata-registry/imr-details/158#:~:text=Definition%3A-,One%20DALY%20represents%20the%20loss%20of%20the%20equivalent%20of%20one,health%20condition%20in%20a%20population.

In [4]:
mental_health = pd.read_csv('/content/mental_health_depression_disorder.csv')

#https://www.kaggle.com/datasets/thedevastator/uncover-global-trends-in-mental-health-disorder

<ipython-input-4-e41f80c1bc89>:1: DtypeWarning: Columns (5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  mental_health = pd.read_csv('/content/mental_health_depression_disorder.csv')

In [5]:
#world_population = pd.read_excel('/content/world_population_excel.xls', skiprows = [0, 1, 2, 3])

#https://data.worldbank.org/indicator/SP.POP.TOTL?most_recent_year_desc=false

#skipping rows: https://stackoverflow.com/questions/20637439/skip-rows-during-csv-import-pandas

#world_population.head()

In [6]:
world_population2 = pd.read_excel('/content/world_population_excel_2.xls')

#Okay so this is the same data set as the last one. I was having trouble importing the original excel format because of the added cells for explanation in the original data set.
#I am going to email Professor Boal asking with this so that I am doing the project fully.

In [30]:
world_population2.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Aruba,ABW,"Population, total",SP.POP.TOTL,54608.0,55811.0,56682.0,57475.0,58178.0,58782.0,...,102880.0,103594.0,104257.0,104874.0,105439.0,105962.0,106442.0,106585.0,106537.0,106445.0
1,Africa Eastern and Southern,AFE,"Population, total",SP.POP.TOTL,130692579.0,134169237.0,137835590.0,141630546.0,145605995.0,149742351.0,...,567892149.0,583651101.0,600008424.0,616377605.0,632746570.0,649757148.0,667242986.0,685112979.0,702977106.0,720839314.0
2,Afghanistan,AFG,"Population, total",SP.POP.TOTL,8622466.0,8790140.0,8969047.0,9157465.0,9355514.0,9565147.0,...,31541209.0,32716210.0,33753499.0,34636207.0,35643418.0,36686784.0,37769499.0,38972230.0,40099462.0,41128771.0
3,Africa Western and Central,AFW,"Population, total",SP.POP.TOTL,97256290.0,99314028.0,101445032.0,103667517.0,105959979.0,108336203.0,...,387204553.0,397855507.0,408690375.0,419778384.0,431138704.0,442646825.0,454306063.0,466189102.0,478185907.0,490330870.0
4,Angola,AGO,"Population, total",SP.POP.TOTL,5357195.0,5441333.0,5521400.0,5599827.0,5673199.0,5736582.0,...,26147002.0,27128337.0,28127721.0,29154746.0,30208628.0,31273533.0,32353588.0,33428486.0,34503774.0,35588987.0

In [7]:
burden.head()

,Entity,Code,Year,"DALYs from depressive disorders per 100,000 people in, both sexes aged age-standardized","DALYs from schizophrenia per 100,000 people in, both sexes aged age-standardized","DALYs from bipolar disorder per 100,000 people in, both sexes aged age-standardized","DALYs from eating disorders per 100,000 people in, both sexes aged age-standardized","DALYs from anxiety disorders per 100,000 people in, both sexes aged age-standardized"
0,Afghanistan,AFG,1990,895.22565,138.24825,147.64412,26.471115,440.33000
1,Afghanistan,AFG,1991,893.88434,137.76122,147.56696,25.548681,439.47202
2,Afghanistan,AFG,1992,892.34973,137.08030,147.13086,24.637949,437.60718
3,Afghanistan,AFG,1993,891.51587,136.48602,146.78812,23.863169,436.69104
4,Afghanistan,AFG,1994,891.39160,136.18323,146.58481,23.189074,436.76800

In [8]:
mental_health.head()

,index,Entity,Code,Year,Schizophrenia (%),Bipolar disorder (%),Eating disorders (%),Anxiety disorders (%),Drug use disorders (%),Depression (%),Alcohol use disorders (%)
0,0,Afghanistan,AFG,1990,0.16056,0.697779,0.101855,4.828830,1.677082,4.071831,0.672404
1,1,Afghanistan,AFG,1991,0.160312,0.697961,0.099313,4.829740,1.684746,4.079531,0.671768
2,2,Afghanistan,AFG,1992,0.160135,0.698107,0.096692,4.831108,1.694334,4.088358,0.670644
3,3,Afghanistan,AFG,1993,0.160037,0.698257,0.094336,4.830864,1.705320,4.096190,0.669738
4,4,Afghanistan,AFG,1994,0.160022,0.698469,0.092439,4.829423,1.716069,4.099582,0.669260

**Merging Datasets:**

What is the purpose?

To transform each of the three dataframes into the same format and merge them into one conglomerate dataframe.

Pseudocode:

1. Convert the column 'Year' from 'burden' to the string datatype.
2. Convert the column 'Year' from 'mental_health' to the string datatype.
3. Merge the dataframes 'burden' and 'mental_health' based on the 'Enity', 'Code', and 'Year' columns.
4. Show the new dataframe 'health_merged'.
5. Show the unique values in the 'Year' column in the 'health_merged' dataframe.
6. Drop the columns 'Indicator Name' and 'Indicator Code' from the 'health_merged' and name the new dataframe 'population'.
7. Show the first five rows from 'population'.
8. Create a new dataset 'population2' by stacking the dataframe and resetting the index.
9. Show the dataframe 'population2'.
10. Set the columns of 'population2' to the titles 'Entity', 'Code', 'Year', and 'Total_Population'.
11. Show the first five rows of 'population2'.
12. Create a new dataframe 'second_merge' by merging the 'health_merged' dataframe with the 'population2' dataframe based on the columns 'Entity', 'Code', and 'Year'.
13. Drop the column 'index' from the dataframe 'second_merge'.
14. Show the first five rows of 'second_merge".

In [2]:
#This was my first merge. I realized I could merge on the first three columns in both dataframes.
#To do that I had to make sure they all had the same data types.

#burden.merge(mental_health, on = 'Entity')

In [9]:
burden['Year'] = burden['Year'].values.astype(str)
mental_health['Year'] = mental_health['Year'].values.astype(str)


#In this cell I am converting each of the year columns to a string. The reason I do this is because when using 'pd.merge' an error was raised stating I was trying to merge a string and a int64.
#I assume that in one of the two data frames the year was a string and the other it was an integer.

#https://sparkbyexamples.com/pandas/pandas-convert-columns-to-string-type/

In [10]:
health_merged = pd.merge(burden, mental_health, on = ['Entity', 'Code', 'Year'])

In [11]:
health_merged

,Entity,Code,Year,"DALYs from depressive disorders per 100,000 people in, both sexes aged age-standardized","DALYs from schizophrenia per 100,000 people in, both sexes aged age-standardized","DALYs from bipolar disorder per 100,000 people in, both sexes aged age-standardized","DALYs from eating disorders per 100,000 people in, both sexes aged age-standardized","DALYs from anxiety disorders per 100,000 people in, both sexes aged age-standardized",index,Schizophrenia (%),Bipolar disorder (%),Eating disorders (%),Anxiety disorders (%),Drug use disorders (%),Depression (%),Alcohol use disorders (%)
0,Afghanistan,AFG,1990,895.22565,138.24825,147.64412,26.471115,440.33000,0,0.16056,0.697779,0.101855,4.82883,1.677082,4.071831,0.672404
1,Afghanistan,AFG,1990,895.22565,138.24825,147.64412,26.471115,440.33000,6659,3.499982,4.647815,12412000,NaN,NaN,NaN,NaN
2,Afghanistan,AFG,1990,895.22565,138.24825,147.64412,26.471115,440.33000,54467,10.318504,4039.755763,12412000,NaN,NaN,NaN,NaN
3,Afghanistan,AFG,1990,895.22565,138.24825,147.64412,26.471115,440.33000,102085,318435.8137,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,AFG,1991,893.88434,137.76122,147.56696,25.548681,439.47202,1,0.160312,0.697961,0.099313,4.82974,1.684746,4.079531,0.671768
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23255,Zimbabwe,ZWE,2017,547.62270,127.46505,115.32798,20.791725,302.88626,108552,340583.1574,NaN,NaN,NaN,NaN,NaN,NaN
23256,Zimbabwe,ZWE,2018,546.57184,127.68121,115.42796,20.916480,301.58250,54274,NaN,NaN,14439000,NaN,NaN,NaN,NaN
23257,Zimbabwe,ZWE,2018,546.57184,127.68121,115.42796,20.916480,301.58250,102082,NaN,NaN,14439000.0,NaN,NaN,NaN,NaN
23258,Zimbabwe,ZWE,2019,544.53160,128.21603,115.38145,21.011127,298.20325,54275,NaN,NaN,14645000,NaN,NaN,NaN,NaN
23259,Zimbabwe,ZWE,2019,544.53160,128.21603,115.38145,21.011127,298.20325,102083,NaN,NaN,14645000.0,NaN,NaN,NaN,NaN

In [12]:
health_merged['Year'].unique()
#Trying to see the range of years in this data set. I would like to try to find world population data from that year range.

array(['1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997',
       '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005',
       '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019'], dtype=object)

In [13]:
population = world_population2.drop(['Indicator Name', 'Indicator Code'], axis = 1)

#Dropping those two columns so that I can hopefully unpivot this data.

In [14]:
population.head()

,Country Name,Country Code,1960,1961,1962,1963,1964,1965,1966,1967,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Aruba,ABW,54608.0,55811.0,56682.0,57475.0,58178.0,58782.0,59291.0,59522.0,...,102880.0,103594.0,104257.0,104874.0,105439.0,105962.0,106442.0,106585.0,106537.0,106445.0
1,Africa Eastern and Southern,AFE,130692579.0,134169237.0,137835590.0,141630546.0,145605995.0,149742351.0,153955516.0,158313235.0,...,567892149.0,583651101.0,600008424.0,616377605.0,632746570.0,649757148.0,667242986.0,685112979.0,702977106.0,720839314.0
2,Afghanistan,AFG,8622466.0,8790140.0,8969047.0,9157465.0,9355514.0,9565147.0,9783147.0,10010030.0,...,31541209.0,32716210.0,33753499.0,34636207.0,35643418.0,36686784.0,37769499.0,38972230.0,40099462.0,41128771.0
3,Africa Western and Central,AFW,97256290.0,99314028.0,101445032.0,103667517.0,105959979.0,108336203.0,110798486.0,113319950.0,...,387204553.0,397855507.0,408690375.0,419778384.0,431138704.0,442646825.0,454306063.0,466189102.0,478185907.0,490330870.0
4,Angola,AGO,5357195.0,5441333.0,5521400.0,5599827.0,5673199.0,5736582.0,5787044.0,5827503.0,...,26147002.0,27128337.0,28127721.0,29154746.0,30208628.0,31273533.0,32353588.0,33428486.0,34503774.0,35588987.0

In [15]:
population = population.set_index(["Country Name", "Country Code"])
population.head()

#Because I am trying to pivot the data, I am converting the country name and country code to the index.
#This will allow me to make the year one single column.

,,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
Country Name,Country Code,,,,,,,,,,,,,,,,,,,,,
Aruba,ABW,54608.0,55811.0,56682.0,57475.0,58178.0,58782.0,59291.0,59522.0,59471.0,59330.0,...,102880.0,103594.0,104257.0,104874.0,105439.0,105962.0,106442.0,106585.0,106537.0,106445.0
Africa Eastern and Southern,AFE,130692579.0,134169237.0,137835590.0,141630546.0,145605995.0,149742351.0,153955516.0,158313235.0,162875171.0,167596160.0,...,567892149.0,583651101.0,600008424.0,616377605.0,632746570.0,649757148.0,667242986.0,685112979.0,702977106.0,720839314.0
Afghanistan,AFG,8622466.0,8790140.0,8969047.0,9157465.0,9355514.0,9565147.0,9783147.0,10010030.0,10247780.0,10494489.0,...,31541209.0,32716210.0,33753499.0,34636207.0,35643418.0,36686784.0,37769499.0,38972230.0,40099462.0,41128771.0
Africa Western and Central,AFW,97256290.0,99314028.0,101445032.0,103667517.0,105959979.0,108336203.0,110798486.0,113319950.0,115921723.0,118615741.0,...,387204553.0,397855507.0,408690375.0,419778384.0,431138704.0,442646825.0,454306063.0,466189102.0,478185907.0,490330870.0
Angola,AGO,5357195.0,5441333.0,5521400.0,5599827.0,5673199.0,5736582.0,5787044.0,5827503.0,5868203.0,5928386.0,...,26147002.0,27128337.0,28127721.0,29154746.0,30208628.0,31273533.0,32353588.0,33428486.0,34503774.0,35588987.0

In [16]:
population2 = population.stack().reset_index()

In [17]:
population2

      Country Name Country Code level_2           0
0            Aruba          ABW    1960     54608.0
1            Aruba          ABW    1961     55811.0
2            Aruba          ABW    1962     56682.0
3            Aruba          ABW    1963     57475.0
4            Aruba          ABW    1964     58178.0
...            ...          ...     ...         ...
16660     Zimbabwe          ZWE    2018  15052184.0
16661     Zimbabwe          ZWE    2019  15354608.0
16662     Zimbabwe          ZWE    2020  15669666.0
16663     Zimbabwe          ZWE    2021  15993524.0
16664     Zimbabwe          ZWE    2022  16320537.0

[16665 rows x 4 columns]

In [18]:
population2.columns = ['Entity', 'Code', 'Year', 'Total_Population']
#Changing the names to match the previous two data sets.

In [19]:
population2.head()

  Entity Code  Year  Total_Population
0  Aruba  ABW  1960           54608.0
1  Aruba  ABW  1961           55811.0
2  Aruba  ABW  1962           56682.0
3  Aruba  ABW  1963           57475.0
4  Aruba  ABW  1964           58178.0

In [20]:
second_merge = pd.merge(health_merged, population2, how = 'left', on = ['Entity', 'Code', 'Year'])

#I used a left merge so that I would only be pulling records from 'population2' that matched records from 'health_merged'.
#I can see by comparing that 'second_merge' and 'health_merged' both have 23,260 rows. I was going to try to right an expression to show that.
#The only thing I could think to do was try to use the shape function to prove they were both the same but they actually have a different number of columns so I cant.
#Either way my point stands that I only returned the records matching from health_merged.

In [21]:
second_merge

,Entity,Code,Year,"DALYs from depressive disorders per 100,000 people in, both sexes aged age-standardized","DALYs from schizophrenia per 100,000 people in, both sexes aged age-standardized","DALYs from bipolar disorder per 100,000 people in, both sexes aged age-standardized","DALYs from eating disorders per 100,000 people in, both sexes aged age-standardized","DALYs from anxiety disorders per 100,000 people in, both sexes aged age-standardized",index,Schizophrenia (%),Bipolar disorder (%),Eating disorders (%),Anxiety disorders (%),Drug use disorders (%),Depression (%),Alcohol use disorders (%),Total_Population
0,Afghanistan,AFG,1990,895.22565,138.24825,147.64412,26.471115,440.33000,0,0.16056,0.697779,0.101855,4.82883,1.677082,4.071831,0.672404,10694796.0
1,Afghanistan,AFG,1990,895.22565,138.24825,147.64412,26.471115,440.33000,6659,3.499982,4.647815,12412000,NaN,NaN,NaN,NaN,10694796.0
2,Afghanistan,AFG,1990,895.22565,138.24825,147.64412,26.471115,440.33000,54467,10.318504,4039.755763,12412000,NaN,NaN,NaN,NaN,10694796.0
3,Afghanistan,AFG,1990,895.22565,138.24825,147.64412,26.471115,440.33000,102085,318435.8137,NaN,NaN,NaN,NaN,NaN,NaN,10694796.0
4,Afghanistan,AFG,1991,893.88434,137.76122,147.56696,25.548681,439.47202,1,0.160312,0.697961,0.099313,4.82974,1.684746,4.079531,0.671768,10745167.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23255,Zimbabwe,ZWE,2017,547.62270,127.46505,115.32798,20.791725,302.88626,108552,340583.1574,NaN,NaN,NaN,NaN,NaN,NaN,14751101.0
23256,Zimbabwe,ZWE,2018,546.57184,127.68121,115.42796,20.916480,301.58250,54274,NaN,NaN,14439000,NaN,NaN,NaN,NaN,15052184.0
23257,Zimbabwe,ZWE,2018,546.57184,127.68121,115.42796,20.916480,301.58250,102082,NaN,NaN,14439000.0,NaN,NaN,NaN,NaN,15052184.0
23258,Zimbabwe,ZWE,2019,544.53160,128.21603,115.38145,21.011127,298.20325,54275,NaN,NaN,14645000,NaN,NaN,NaN,NaN,15354608.0
23259,Zimbabwe,ZWE,2019,544.53160,128.21603,115.38145,21.011127,298.20325,102083,NaN,NaN,14645000.0,NaN,NaN,NaN,NaN,15354608.0

In [ ]:
#second_merge.fillna(0)
#I am not sure if I should fill all of these nan values or not yet. It could affect aggregation I think.

In [22]:
second_merge = second_merge.drop(['index'], axis= 1)

In [23]:
second_merge.head()

,Entity,Code,Year,"DALYs from depressive disorders per 100,000 people in, both sexes aged age-standardized","DALYs from schizophrenia per 100,000 people in, both sexes aged age-standardized","DALYs from bipolar disorder per 100,000 people in, both sexes aged age-standardized","DALYs from eating disorders per 100,000 people in, both sexes aged age-standardized","DALYs from anxiety disorders per 100,000 people in, both sexes aged age-standardized",Schizophrenia (%),Bipolar disorder (%),Eating disorders (%),Anxiety disorders (%),Drug use disorders (%),Depression (%),Alcohol use disorders (%),Total_Population
0,Afghanistan,AFG,1990,895.22565,138.24825,147.64412,26.471115,440.33000,0.16056,0.697779,0.101855,4.82883,1.677082,4.071831,0.672404,10694796.0
1,Afghanistan,AFG,1990,895.22565,138.24825,147.64412,26.471115,440.33000,3.499982,4.647815,12412000,NaN,NaN,NaN,NaN,10694796.0
2,Afghanistan,AFG,1990,895.22565,138.24825,147.64412,26.471115,440.33000,10.318504,4039.755763,12412000,NaN,NaN,NaN,NaN,10694796.0
3,Afghanistan,AFG,1990,895.22565,138.24825,147.64412,26.471115,440.33000,318435.8137,NaN,NaN,NaN,NaN,NaN,NaN,10694796.0
4,Afghanistan,AFG,1991,893.88434,137.76122,147.56696,25.548681,439.47202,0.160312,0.697961,0.099313,4.82974,1.684746,4.079531,0.671768,10745167.0

**next thing:**

In [25]:
second_merge.shape

(23260, 16)

In [26]:
second_merge["Entity"].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'American Samoa', 'Andorra',
       'Angola', 'Antigua and Barbuda', 'Argentina', 'Armenia',
       'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain',
       'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin',
       'Bermuda', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina',
       'Botswana', 'Brazil', 'Brunei', 'Bulgaria', 'Burkina Faso',
       'Burundi', 'Cambodia', 'Cameroon', 'Canada', 'Cape Verde',
       'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia',
       'Comoros', 'Congo', 'Cook Islands', 'Costa Rica', "Cote d'Ivoire",
       'Croatia', 'Cuba', 'Cyprus', 'Democratic Republic of Congo',
       'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador',
       'Egypt', 'El Salvador', 'England', 'Equatorial Guinea', 'Eritrea',
       'Estonia', 'Ethiopia', 'Fiji', 'Finland', 'France', 'Gabon',
       'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Greenland',
       'Grenada', 'Guam', 'Guatemala', 'Guinea', 'Guinea-Bissau',
       'Guyana', 'Haiti', 'Honduras', 'Hungary', 'Iceland', 'India',
       'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy',
       'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati',
       'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho',
       'Liberia', 'Libya', 'Lithuania', 'Luxembourg', 'Madagascar',
       'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta',
       'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico',
       'Micronesia (country)', 'Moldova', 'Monaco', 'Mongolia',
       'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia',
       'Nauru', 'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua',
       'Niger', 'Nigeria', 'Niue', 'North Korea', 'Northern Ireland',
       'Northern Mariana Islands', 'Norway', 'Oman', 'Pakistan', 'Palau',
       'Palestine', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru',
       'Philippines', 'Poland', 'Portugal', 'Puerto Rico', 'Qatar',
       'Romania', 'Russia', 'Rwanda', 'Saint Kitts and Nevis',
       'Saint Lucia', 'Saint Vincent and the Grenadines', 'Samoa',
       'San Marino', 'Sao Tome and Principe', 'Saudi Arabia', 'Scotland',
       'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore',
       'Slovakia', 'Slovenia', 'Solomon Islands', 'Somalia',
       'South Africa', 'South Korea', 'South Sudan', 'Spain', 'Sri Lanka',
       'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Syria', 'Taiwan',
       'Tajikistan', 'Tanzania', 'Thailand', 'Togo', 'Tokelau', 'Tonga',
       'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan',
       'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates',
       'United Kingdom', 'United States', 'United States Virgin Islands',
       'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela', 'Vietnam',
       'Wales', 'World', 'Yemen', 'Zambia', 'Zimbabwe'], dtype=object)

In [28]:
#Create a new dataframe by grouping the dataset by the entity column with the cell values being based on the mean.
#This shows the data as a representation of each country through out the entire timespan of the dataset.

average_country = second_merge.groupby(['Entity'], dropna = True).mean()

<ipython-input-28-08ad7db0df3a>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  average_country = second_merge.groupby(['Entity'], dropna = True).mean()

In [30]:
average_country.head()

,"DALYs from depressive disorders per 100,000 people in, both sexes aged age-standardized","DALYs from schizophrenia per 100,000 people in, both sexes aged age-standardized","DALYs from bipolar disorder per 100,000 people in, both sexes aged age-standardized","DALYs from eating disorders per 100,000 people in, both sexes aged age-standardized","DALYs from anxiety disorders per 100,000 people in, both sexes aged age-standardized",Anxiety disorders (%),Drug use disorders (%),Depression (%),Alcohol use disorders (%),Total_Population
Entity,,,,,,,,,,
Afghanistan,891.439232,134.557475,147.338742,22.244785,441.869142,4.848102,2.120798,4.118622,0.663151,2.349833e+07
Albania,380.798234,182.608821,117.604567,24.276284,357.725068,3.368903,0.498765,2.190442,1.746757,3.037435e+06
Algeria,737.917726,160.215775,163.923680,41.403746,448.726377,5.011396,1.540640,3.657743,0.653712,3.306776e+07
American Samoa,391.672482,197.008410,59.819785,27.934088,378.077479,3.293312,0.759355,2.940850,1.135266,5.404374e+04
Andorra,622.872239,183.942241,200.835335,106.081797,518.685642,5.279751,0.885044,3.739451,1.224082,6.905838e+04

In [36]:
def how_many(df, column):



  for row in df:
    number = (df['column']/100) * df['Total_Population']


  return number




#https://www.freecodecamp.org/news/how-to-iterate-over-rows-with-pandas-loop-through-a-dataframe/

In [37]:
how_many(average_country, 'Anxiety disorders (%)')

KeyError: ignored

**Testing Datasets:**

This section is for uploading data sets to see if they are going to be something we can work through. It is easier for me to get a handle of what I am looking at once I upload it to colab so these are the ones that were not used.

In [ ]:
#facility = pd.read_excel('/content/health_facility_locations.xlsx')
#facility.head()
#facility.columns
#facility['FACNAME'].value_counts

In [ ]:
#ssi2021 = pd.read_csv('/content/Surgical-Site-Infections-California-Hospitals-2021.csv', encoding='UTF-8')
#https://catalog.data.gov/dataset/surgical-site-infections-ssis-for-operative-procedures-in-california-hospitals-62337

#ssi2022 = pd.read_csv('https://catalog.data.gov/dataset/surgical-site-infections-ssis-for-operative-procedures-in-california-hospitals-62337',)
#https://catalog.data.gov/dataset/surgical-site-infections-ssis-for-operative-procedures-in-california-hospitals-62337

In [ ]:
#with open('/content/Surgical-Site-Infections-California-Hospitals-2021.csv') as f:
   # print(f)


#When trying to upload these files into colab I am getting an error stating it is unable to

<_io.TextIOWrapper name='/content/Surgical-Site-Infections-California-Hospitals-2021.csv' mode='r' encoding='UTF-8'>

In [ ]:
#ocd_patient = pd.read_csv('/content/ocd_patient_dataset.csv')

In [ ]:
#vax = pd.read_csv('/content/Special_Vaccine_Locations.csv')

#https://catalog.data.gov/dataset/special-vaccine-locations

#vax.head()

In [ ]:
#mi = pd.read_csv('/content/myocardial+infarction+complications.zip')
#mi.head()

#social = pd.read_csv('/content/archive.zip')
#social.head()

In [ ]:
#ocd_patient.head()

In [ ]:
#ocd_json = pd.read_json('https://www.ebi.ac.uk/biostudies/files/S-EPMC2943932/S-EPMC2943932.json')

#ocd_json = json.load(open('/content/OCD.json'))
#ocd_json = pd.DataFrame(ocd_json)

#This is a JSON data set I was trying to juse that kept not running properly. I may use it again but I think because of the way it is formatted it will be tough for me to use.

In [ ]:
#student = pd.read_csv('/content/archive (1).zip')
#student.head()

**Websites:**

Creating a folder for github:

*   https://berrasari.medium.com/creating-folders-on-github-a-step-by-step-guide-fb0b44b98561#:~:text=Steps%20to%20Create%20Folders%20on%20GitHub&text=Choose%20the%20repository%20where%20you,the%20slash%20at%20the%20end.

Kaggle OCD dataset:

*   https://www.kaggle.com/datasets/ohinhaque/ocd-patient-dataset-demographics-and-clinical-data

Chat gpt webpage week 13 assignment:

*   https://chat.openai.com/share/50db56ab-ffcb-405d-869a-9f4e6f04b76c

Predictors and moderators of treatment outcome in the Pediatric Obsessive Compulsive Treatment Study (POTS I) AND its accompanying JSON file. This is the one that would not work.

*   https://www.ebi.ac.uk/biostudies/europepmc/studies/S-EPMC2943932
*   https://www.ebi.ac.uk/biostudies/files/S-EPMC2943932/S-EPMC2943932.json

Social Media and Mental Health: archive data frame

*   https://www.kaggle.com/datasets/souvikahmed071/social-media-and-mental-health

Student Mental Health: archive(1).zip:

*   https://www.kaggle.com/datasets/shariful07/student-mental-health